spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <Your MySQL URL here>
    username: <Your MySQL username here>
    password: <Your MySQL password here>
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <Your API Key here>
      embedding-model:
        model-name: text-embedding-v4
        api-key: <You API Key here>
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
bigmodel:
  api-key: <Your Api Key>